apiVersion: v1
kind: Service
metadata:
  name: obmovies-app-service
spec:
  selector:
    app: obmovies-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: obmovies-app-deployment
spec:
  selector:
    matchLabels:
      app: obmovies-app
  replicas: 2
  template:
    metadata:
      labels:
        app: obmovies-app
    spec:
      containers:
      - name: obmovies-app
        image: obmoviesacr.azurecr.io/obmovies-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
