apiVersion: v1
kind: Service
metadata:
  name: obmovies-service
spec:
  selector:
    app: obmovies-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: obmovies-app
spec:
  selector:
    matchLabels:
      app: obmovies-app
  replicas: 5
  template:
    metadata:
      labels:
        app: obmovies-app
    spec:
      containers:
      - name: obmovies-app
        image: obmovies-app
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000